name: ActionSSHTest
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '通过SSH连接Github Actions'
        required: false
        default: false
        type: boolean
      debug:
        description: 'Debug Github Actions'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: 退出Action
      if: ${{ inputs.debug == true }}
      run: |
        exit 1
    
    - name: Enable SSH
      if: ${{ inputs.ssh == true }}
      run: |
        echo "SSH on!"

    - name: Disable SSH
      if: ${{ inputs.ssh == false }}
      run: |
        cat /proc/cpuinfo
        if [ ${{ inputs.debug }} == "false" ]; then
          echo 退出
        fi
        echo "SSH off!"
